### ISSUE TITLE
Title of the page change unexpectedly 

### ISSUE THREAD

**Issue by sikaxn** [XiaoyiWang98/ToDoStopWatch#2]
as show in the picture, sometimes when add a todo item what you enter goes into the title. 

![5ED08FF3-A25B-4FAF-B176-4FCFDC53DBA2](https://user-images.githubusercontent.com/6559079/116628858-000e9200-a91e-11eb-87c7-887eed734968.png)
![1FC7E242-0455-4778-8A29-991F1D670C5F](https://user-images.githubusercontent.com/6559079/116629010-54b20d00-a91e-11eb-93ad-2742f92bece3.png)
![E4DA0EC1-D71B-4FFB-978D-09474A36ECB5](https://user-images.githubusercontent.com/6559079/116629017-58459400-a91e-11eb-8db3-61e443055bfb.jpeg)

**Comment by seanxyw** [comment]
Partically fixed. The problem is about UX and cannot be truely fixed.
